#' This function takes in tables with Euclidean distance scores generated by Nik and outputs heatmaps comparing types
#' and makes those heatmaps clickable to navigate to their corresponding cell type card.
#' 
#' @param main_confusion - data frame of pairwise comparisons with Euclidean distance values and reverse scaled values, output
#'                         by Nik's script, with the main species featured indicated as "cluster_1" (see script and accompanying files) 
#' 
#' @param main_cldf - standard annotated cluster table for the main species featured
#' 
#' @param node - character string giving the name of the type featured on the card
#' 
#' @param spec1 - characer string giving the name of the first species to compare against
#' 
#' @param spec1_tbl - data frame indicating homologous types between the main species and first species to compare against. This is
#'                    a manually edited version of the supplementary table from Bakken et al., 2021
#'                    
#' @param spec1_cldf - standard annotated cluster table for species 1
#' 
#' @param spec1_nom - nomenclature table for species 1 (used to build links to cell type cards)
#' 
#' Remaining arguments are the same, except for species 2




plot_cross_species_heatmaps <- function(main_confusion,
                                        main_cldf,
                                        node,
                                        spec1,
                                        spec1_tbl,
                                        spec1_cldf,
                                        spec1_nom,
                                        spec2,
                                        spec2_tbl,
                                        spec2_cldf,
                                        spec2_nom){
  
  
  suppressPackageStartupMessages({
    library(ggpubr)
    library(grid)
    library(cowplot)
    library(scales)
    library(gridExtra)
    library(grImport2)
    library(rsvg)
    library(gridSVG)
  })
  
  # Clear all plots and grob
  #dev.off(dev.list()["RStudioGD"])
  
  # Create discrete color scale to keep coloring consistent between the two plots
  x <- round(seq(0, 1, length.out = 101),2)
  y <- seq_gradient_pal("#fff8ef", "orangered")(x)
  names(y) <- x
  hicols <- y
  main_confusion_2 <- main_confusion
  
  
  # Identify taxonomy CCNs for building hyperlinks
  if (spec1 == "marmoset"){
    tax1 <- "CCN201912132"
  }
  if (spec1 == "mouse"){
    tax1 <- "CCN202002013"
  }
  if (spec1 == "human"){
    tax1 <- "CCN201912131"
  }
  
  if (spec2 == "marmoset"){
    tax2 <- "CCN201912132"
  }
  if (spec2 == "mouse"){
    tax2 <- "CCN202002013"
  }
  if (spec2 == "human"){
    tax2 <- "CCN201912131"
  }
  
  
  
  # Pick species 1 types to compare to
  spec1_homologs <- unlist(unname(spec1_tbl[spec1_tbl$cluster_label == node,4:ncol(spec1_tbl)]))
  spec1_homologs <- spec1_homologs[!is.na(spec1_homologs)]
  temp_homologs <- spec1_homologs
  
  if (length(spec1_homologs) > 0) {
    compare_subs <- unique(spec1_cldf$subclass_label[spec1_cldf$cluster_label %in% spec1_homologs])
    spec1_compare <- sort(unique(c(spec1_homologs, spec1_cldf$cluster_label[spec1_cldf$subclass_label %in% compare_subs])))
    
    main_confusion$cluster_2[main_confusion$cluster_2 %in% spec1_homologs] <- paste0("\u25b6",main_confusion$cluster_2[main_confusion$cluster_2 %in% spec1_homologs])
    
    spec1_compare[match(spec1_homologs,spec1_compare)] <- paste0("\u25b6",spec1_compare[match(spec1_homologs,spec1_compare)])
    spec1_homologs <- paste0("\u25b6",spec1_homologs)
    
    # Identify which boxes to highlight
    frame_sub1 <- subset(main_confusion,cluster_2 %in% spec1_compare & cluster_1 %in% node)
    clust1 <- spec1_cldf$cluster_label[spec1_cldf$subclass_label %in% compare_subs]
    clust1[clust1 %in% temp_homologs] <- paste0("\u25b6",clust1[clust1 %in% temp_homologs])
    frame_sub1 <- frame_sub1[match(clust1,frame_sub1$cluster_2),]
    frame_sub1$cluster_2 <- factor(frame_sub1$cluster_2,rev(clust1))
    frame_sub1 <- frame_sub1[order(frame_sub1$cluster_2),]
    frames1 <- as.data.frame(which(frame_sub1$cluster_2 %in% spec1_homologs, arr.ind = TRUE))
    colnames(frames1) <- "row"
    
    # Make first plot
    p1 <- ggplot() + 
      geom_tile(data = frame_sub1, aes(x=cluster_1, y=cluster_2, fill=as.factor(round(as.numeric(scaled_dist),2)))) + 
      theme_classic() +
      theme(axis.title.x = element_text(vjust=-1.2),
            axis.title.y.left = element_text(vjust=2,size=18),
            axis.text.x = element_blank(),
            axis.text.y.left = element_text(size = 12,margin = margin(t = 0, r = 0, b = 0, l = 40),color = linkcolor),
            axis.title.x.top = element_blank(),
            axis.ticks = element_blank(),
            panel.border = element_blank(),
            plot.margin = unit(c(0.5, .75, .5, .5), "cm"),
            axis.line = element_blank(),
            panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            legend.position = "none",
            legend.title = element_text(size = 8),
            text = element_text(family = "Arial")) +
      scale_fill_manual(values = hicols, aesthetics = c("colour", "fill")) +
      scale_y_discrete(position = "left", labels = function(x) str_wrap(x, width = 10)) +
      scale_x_discrete(position = "top") +
      labs(y = str_to_title(spec1), fill = "Similarity") + 
      geom_text(data = frame_sub1, aes(x = cluster_1, y = cluster_2, label = as.factor(round(as.numeric(scaled_dist),2)))) +
      geom_rect(data=frames1, size=0.4, fill=NA, colour="black",
                aes(xmin=0.5, xmax=1.5, ymin=row - 0.5, ymax=row + 0.5))
    
  }
  
  
  # If there are no homologs identified, plot the data and don't highlight any boxes
  
  if (length(spec1_homologs) == 0) {
    main_sub <- main_cldf$subclass_label[main_cldf$cluster_label == node]
    compare_subs <- unique(spec1_cldf$subclass_label[spec1_cldf$subclass_label %in% main_sub])
    spec1_compare <- sort(unique(c(spec1_cldf$cluster_label[spec1_cldf$subclass_label %in% compare_subs])))
    
    if (length(spec1_compare) == 0) {
      text <- paste0("No ",spec1," homologous cell types found.")
      p1 <- ggplot() + 
        annotate("text", x = 1, y = 1, size=4, label = text) + 
        theme_void()
    }
    
    if (length(spec1_compare) > 0) {
      
      frame_sub1 <- subset(main_confusion,cluster_2 %in% spec1_compare & cluster_1 %in% node)
      clust1 <- spec1_cldf$cluster_label[spec1_cldf$subclass_label %in% compare_subs]
      clust1[clust1 %in% temp_homologs] <- paste0("\u25b6",clust1[clust1 %in% temp_homologs])
      frame_sub1 <- frame_sub1[match(clust1,frame_sub1$cluster_2),]
      frame_sub1$cluster_2 <- factor(frame_sub1$cluster_2,rev(clust1))
      frame_sub1 <- frame_sub1[order(frame_sub1$cluster_2),]
      
      # Make first plot
      p1 <- ggplot() + 
        geom_tile(data = frame_sub1, aes(x=cluster_1, y=cluster_2, fill=as.factor(round(as.numeric(scaled_dist),2)))) + 
        theme_classic() +
        theme(axis.title.x = element_text(vjust=-1.2),
              axis.title.y.left = element_text(vjust=2,size=18),
              axis.text.x = element_blank(),
              axis.text.y.left = element_text(size = 12,margin = margin(t = 0, r = 0, b = 0, l = 40),color = linkcolor),
              axis.title.x.top = element_blank(),
              axis.ticks = element_blank(),
              panel.border = element_blank(),
              plot.margin = unit(c(0.5, .75, .5, .5), "cm"),
              axis.line = element_blank(),
              panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(),
              legend.position = "none",
              legend.title = element_text(size = 8),
              text = element_text(family = "Arial")) +
        scale_fill_manual(values = hicols, aesthetics = c("colour", "fill")) +
        scale_y_discrete(position = "left", labels = function(x) str_wrap(x, width = 10)) +
        scale_x_discrete(position = "top") +
        labs(y = str_to_title(spec1), fill = "Similarity") + 
        geom_text(data = frame_sub1, aes(x = cluster_1, y = cluster_2, label = as.factor(round(as.numeric(scaled_dist),2))))
      
    }
  }
  
  # Build links for species 1 
  spec1_compare_accessions <- spec1_nom$accession[spec1_nom$alias %in% gsub("\u25b6","",spec1_compare)]
  spec1_compare_accessions <- paste0("/celltypes/",tax1,"/",spec1_compare_accessions)
  
  
  
  
  # Pick species 2 types to compare to
  spec2_homologs <- unlist(unname(spec2_tbl[spec2_tbl$cluster_label == node,4:ncol(spec2_tbl)]))
  spec2_homologs <- spec2_homologs[!is.na(spec2_homologs)]
  temp_homologs <- spec2_homologs
  
  # If there are homologs identified
  if (length(spec2_homologs) > 0) {
    compare_subs <- unique(spec2_cldf$subclass_label[spec2_cldf$cluster_label %in% spec2_homologs])
    spec2_compare <- sort(unique(c(spec2_homologs, spec2_cldf$cluster_label[spec2_cldf$subclass_label %in% compare_subs])))
    
    main_confusion_2$cluster_2[main_confusion_2$cluster_2 %in% spec2_homologs] <- paste0(main_confusion_2$cluster_2[main_confusion_2$cluster_2 %in% spec2_homologs],"\u25c0")
    
    spec2_compare[match(spec2_homologs,spec2_compare)] <- paste0(spec2_compare[match(spec2_homologs,spec2_compare)],"\u25c0")
    spec2_homologs <- paste0(spec2_homologs,"\u25c0")
    
    # Identify which boxes to highlight
    frame_sub2 <- subset(main_confusion_2,cluster_2 %in% spec2_compare & cluster_1 %in% node)
    clust2 <- spec2_cldf$cluster_label[spec2_cldf$subclass_label %in% compare_subs]
    clust2[clust2 %in% temp_homologs] <- paste0(clust2[clust2 %in% temp_homologs],"\u25c0")
    frame_sub2 <- frame_sub2[match(clust2,frame_sub2$cluster_2),]
    frame_sub2$cluster_2 <- factor(frame_sub2$cluster_2,rev(clust2))
    frame_sub2 <- frame_sub2[order(frame_sub2$cluster_2),]
    frames2 <- as.data.frame(which(frame_sub2$cluster_2 %in% spec2_homologs, arr.ind = TRUE))
    colnames(frames2) <- "row"
    textcolors <- c()
    for (i in 1:nrow(frame_sub2)){
      if (grepl("\u25c0",frame_sub2$cluster_2[i]) == TRUE){
        textcolors[i] <- linkcolor
      }
      else {
        textcolors[i] <- celltypelabelcolor
      }
    }
    # Make second plot
    p2 <- ggplot() + 
      geom_tile(data = frame_sub2, aes(x=cluster_1, y=cluster_2, fill=as.factor(round(as.numeric(scaled_dist),2)))) + 
      theme_classic() +
      theme(axis.title.x = element_text(vjust=-1.2),
            axis.title.y.right = element_text(vjust=2,size=18),
            axis.text.x = element_blank(),
            axis.text.y.right = element_text(size = 12,margin = margin(t = 0, r = 40, b = 0, l = 0),color = linkcolor),
            axis.title.x.top = element_blank(),
            axis.ticks = element_blank(),
            panel.border = element_blank(),
            plot.margin = unit(c(0.5, .75, .5, .5), "cm"),
            axis.line = element_blank(),
            panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            legend.position = "none",
            legend.title = element_text(size = 8),
            text = element_text(family = "Arial")) +
      scale_fill_manual(values = hicols, aesthetics = c("colour", "fill")) +
      scale_y_discrete(position = "right", labels = function(x) str_wrap(x, width = 10)) +
      scale_x_discrete(position = "top") +
      labs(y = str_to_title(spec2), fill = "Similarity") + 
      geom_text(data = frame_sub2, aes(x = cluster_1, y = cluster_2, label = as.factor(round(as.numeric(scaled_dist),2)))) +
      geom_rect(data=frames2, size=0.4, fill=NA, colour="black",
                aes(xmin=0.5, xmax=1.5, ymin=row - 0.5, ymax=row + 0.5))
    
  }
  
  
  # If there are no homologs identified, plot the data and don't highlight any boxes
  
  if (length(spec2_homologs) == 0){
    main_sub <- main_cldf$subclass_label[main_cldf$cluster_label == node]
    compare_subs <- unique(spec2_cldf$subclass_label[spec2_cldf$subclass_label %in% main_sub])
    spec2_compare <- sort(unique(c(spec2_homologs, spec2_cldf$cluster_label[spec2_cldf$subclass_label %in% compare_subs])))
    
    
    if (length(spec2_compare) == 0) {
      text <- paste0("No ",spec2," homologous cell types found.")
      p2 <- ggplot() + 
        annotate("text", x = 1, y = 1, size=4, label = text) + 
        theme_void()
    }
    
    if (length(spec2_compare) > 0) {
      frame_sub2 <- subset(main_confusion_2,cluster_2 %in% spec2_compare & cluster_1 %in% node)
      clust2 <- spec2_cldf$cluster_label[spec2_cldf$subclass_label %in% compare_subs]
      clust2[clust2 %in% temp_homologs] <- paste0(clust2[clust2 %in% temp_homologs],"\u25c0")
      frame_sub2 <- frame_sub2[match(clust2,frame_sub2$cluster_2),]
      frame_sub2$cluster_2 <- factor(frame_sub2$cluster_2,rev(clust2))
      frame_sub2 <- frame_sub2[order(frame_sub2$cluster_2),]
      
      # Make second plot
      p2 <- ggplot() + 
        geom_tile(data = frame_sub2, aes(x=cluster_1, y=cluster_2, fill=as.factor(round(as.numeric(scaled_dist),2)))) + 
        theme_classic() +
        theme(axis.title.x = element_text(vjust=-1.2),
              axis.title.y.right = element_text(vjust=2,size=18),
              axis.text.x = element_blank(),
              axis.text.y.right = element_text(size = 12,margin = margin(t = 0, r = 40, b = 0, l = 0),color = linkcolor),
              axis.title.x.top = element_blank(),
              axis.ticks = element_blank(),
              panel.border = element_blank(),
              plot.margin = unit(c(0.5, .75, .5, .5), "cm"),
              axis.line = element_blank(),
              panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
              legend.position = "none",
              legend.title = element_text(size = 8),
              text = element_text(family = "Arial")) +
        scale_fill_manual(values = hicols, aesthetics = c("colour", "fill")) +
        scale_y_discrete(position = "right", labels = function(x) str_wrap(x, width = 10)) +
        scale_x_discrete(position = "top") +
        labs(y = str_to_title(spec2), fill = "Similarity") + 
        geom_text(data = frame_sub2, aes(x=cluster_1, y=cluster_2, label=as.factor(round(as.numeric(scaled_dist),2))))
      
    }
    
  }
  
  # Build links for species 2
  spec2_compare_accessions <- spec2_nom$accession[spec2_nom$alias %in% gsub("\u25c0","",spec2_compare)]
  spec2_compare_accessions <- paste0("/celltypes/",tax2,"/",spec2_compare_accessions)
  
  # Make plot with legend only
  leg_conf <- main_confusion
  plegend <- ggplot(leg_conf, aes(x=cluster_1, y=cluster_2, fill=round(as.numeric(scaled_dist),2))) + 
    geom_tile() + 
    theme_classic() +
    theme(
      legend.text = element_text(size=10),
      legend.title = element_text(size = 10),
      legend.position='bottom', 
      legend.justification='left',
      legend.direction='horizontal',
      plot.margin = margin(t = 0,  # Top margin
                           r = 0,  # Right margin
                           b = 0,  # Bottom margin
                           l = 1)) +
    scale_fill_gradientn(colors = c("#fee8c8","#fdbb84","#FD7F2C","orangered")) +
    labs(fill = "Similarity")
  
  legendonly <- get_legend(plegend)
  legendonly <- as_ggplot(legendonly)
  
  # Place plots together with ggdraw 
  fp <- ggdraw() +
    draw_plot(p1, 0, 0.06, 0.5, 0.95) +
    draw_plot(p2, 0.5, 0.06, .5, 0.95) +
    draw_plot(legendonly, .4, 0.01, .05, .05)
  
  
  # Force plot into grob
  fp_grob <- fp %>% ggplotGrob() %>% grid.force()
  grid.draw(fp_grob)
  fp_list <- grid.ls()
  
  # Garnish plot grid with hyperlinks
  # Find rect objects
  rectLabels <- grid.grep("geom_rect.rect", grep=TRUE, global=TRUE)
  
  # The selected elements assume the standard two-column + legend heatmap found in cell type cards. If doing a different 
  # number of species, these links will be probably be placed in unexpected places
  
  grid.hyperlink(rectLabels[[1]], href = rev(spec1_compare_accessions), group=FALSE, show = "new")
  grid.hyperlink(rectLabels[[3]], href = rev(spec2_compare_accessions), group=FALSE, show = "new")
  
  # Find text objects
  textLabels <- grid.grep("GRID.text.", grep=TRUE, global=TRUE)
  
  grid.hyperlink(textLabels[[1]], href = rev(spec1_compare_accessions), group=FALSE, show = "new")
  grid.hyperlink(textLabels[[2]], href = rev(spec1_compare_accessions), group=FALSE, show = "new")
  grid.hyperlink(textLabels[[4]], href = rev(spec2_compare_accessions), group=FALSE, show = "new")
  grid.hyperlink(textLabels[[5]], href = rev(spec2_compare_accessions), group=FALSE, show = "new")
  
  # Save plot
  grid.export(paste0(gsub("/","-",node),"_cross_species_heatmap.svg"))
  
  # Read and brute-force replace xlink:href with href. xlink:href is deprecated
  tempfile <- readLines(file(paste0(gsub("/","-",node),"_cross_species_heatmap.svg")))
  tempfile <- gsub("xlink:href", "href", tempfile)
  writeLines(tempfile, file(paste0(gsub("/","-",node),"_cross_species_heatmap.svg")))
  
  # Clear all plots and grob
  dev.off(dev.list()["RStudioGD"])
  rm(fp,fp_grob,fp_list,rectLabels,textLabels,tempfile)
}
